services:
  postgres:
    image: postgres:16-alpine
    container_name: loggerregister-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: loggerregisterdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  rabbitmq:
    image: rabbitmq:management
    container_name: loggerregister-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/lib/rabbitmq/log

volumes:
  rabbitmq_data:
  rabbitmq_logs:
  postgres_data:

networks:
  default:
    name: loggerregister-network